DROP USER EMPLOYEES CASCADE;
CREATE USER EMPLOYEES IDENTIFIED BY EMPLOYEES;
GRANT CONNECT,RESOURCE,dba TO EMPLOYEES;
GRANT UNLIMITED TABLESPACE TO EMPLOYEES;
ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
CONNECT EMPLOYEES/EMPLOYEES@LOCALHOST:1521/XEPDB1;